### ISSUE TITLE
deps and conda_deps

### ISSUE THREAD

**Issue by nabobalis** [drdavella/tox-conda#4]
So I wanted to see if I could just pip install everything and had nothing but `deps` in my tox env. (I wanted to race pip vs conda installs on Travis).

But [here](https://travis-ci.org/nabobalis/sunpy/jobs/452017188#L525) if you don't have `conda_deps` it conda installs and then seems to pip install the same package list. 
Is that meant to happen?

**Comment by drdavella** [comment]
Hi @nabobalis, thanks for the interest, and sorry for the late response!

This shouldn't be the case, but I can't reproduce it locally. Are you still having this issue?

**Comment by nabobalis** [comment]
I wish I had saved a link the commit and the CI run for it. 

At the time, I was just playing around with just listing pip deps and not using conda  and I saw this happen. 

I will see if I can replicate it again with a small example and get back to you soon(ish).

**Comment by nabobalis** [comment]
Oh I think I know what happened and it was my fault.

**Comment by drdavella** [comment]
Easy fix 😁
